### PR TITLE
Added generate tile method

### PR DESCRIPTION
**Pull request by HeDo88TH**
Ref https://github.com/DroneDB/Registry/issues/97

### CODE REVIEW

**Comment by HeDo88TH** [comment]
I don't know why on windows DDB keeps the TIF file open and makes the test fail. Do you have any clues @pierotofy ?

**Comment by pierotofy** [comment]
It's possible we're missing to close a file handle in the C++ code.

**Comment by HeDo88TH** [comment]
@pierotofy We should merge this 👍

**Comment by pierotofy** [comment]
Ups, forgot about it.

Looks good to me.

**Pull request merged**
