### PR TITLE
Add tag and sync support

### PR DESCRIPTION
**Pull request by HeDo88TH**
Support PR for https://github.com/DroneDB/DroneDB/pull/195

### CODE REVIEW

**Comment by HeDo88TH** [comment]
Still working on it

**Comment by HeDo88TH** [comment]
The tests fail because it uses endpoints from https://github.com/DroneDB/DroneDB/pull/195 that is not merged yet
We should merge this anyways. @pierotofy you can test it in local after pulling the latest changes from ddb https://github.com/DroneDB/DroneDB/pull/195

**Comment by pierotofy** [comment]
> The tests fail because it uses endpoints that is not merged yet

One more reason for making small pull requests in the future (one branch per feature). Function signatures seem to match OK. I'll trust it works.

**Comment by HeDo88TH** [comment]
Actually 
depends

**Pull request merged**
