### PR TITLE
Various fixes and improvement

### PR DESCRIPTION
**Pull request by HeDo88TH**
API cleanup, fix and tests improvement

### CODE REVIEW

**Review by pierotofy — COMMENTED** [review]
1. There's no need to check for `null` in the API call results; the API will *always* return JSON, or throw an exception. There are no other cases.
2. Why change `JToken` to `object`? The result is either going to be a scalar, a JSON array or a JSON object (the definition of JToken). object is what?

**Comment by pierotofy** [comment]
The meta get needs to be fixed, but careful that it's not always an array.

If the key is singular `config`, `info`, etc. the result is an object (single meta).

If the key is plural `annotations`, `notes`, etc. the result is an array (multiple metas).

**Comment by pierotofy** [comment]
(CI is failing also)

**Comment by HeDo88TH** [comment]
> 1. There's no need to check for `null` in the API call results; the API will _always_ return JSON, or throw an exception. There are no other cases.

NULL can always happen, it's a good practice to check for it. Maybe now the code behind does not return null in any case but whan about the future? A simple null check will probably save debugging hours down the road.

> 2. Why change `JToken` to `object`? The result is either going to be a scalar, a JSON array or a JSON object (the definition of JToken). object is what?

It's bad practice to return an external library object type in a public API. It will force all the clients to include that library, causing all sorts of problems (duplication, version conflict, etc...). 
Instead the `object` type is the ancestor of all the other types in C#, it's perfectly fine to return it. If you need a JObject you can always convert it.

> The meta get needs to be fixed (good catch), but careful that it's not always an array.
> If the key is singular `config`, `info`, etc. the result is an object (single meta).
> If the key is plural `annotations`, `notes`, etc. the result is an array (multiple metas).

I knew this kind of thing would haunt us in the future but I didn't think so soon.

> (CI is failing also)
I am fixing it

**Comment by pierotofy** [comment]
> NULL can always happen, it's a good practice to check for it. 

Or add extra complexity... ok keep them.

> It's bad practice to return an external library object type

Bho. Disagree, but keep it. You're doing unnecessary serialization/unserialization down the road.

**Comment by pierotofy** [comment]
:+1:

**Pull request merged**
